version: '3.7'
services:
  e2e:
    build:
      dockerfile: Dockerfile
      context: e2e-cypress
    depends_on:
      - webapp
    volumes:
      - ./e2e-cypress/cypress/screenshots:/app/cypress/screenshots

  webapp:
    environment:
      - AUTH0_BASE_URL=http://webapp:3000

