services:
  webapp:
    build:
      dockerfile: Dockerfile
      context: ./webapp-nextjs
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - .env:/app/.env.local
    

     