services:
  webapp:
    build:
      context: ./webapp-htmx-go
      dockerfile: Dockerfile
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - AUTH0_CALLBACK_URL=http://webapp:3000/callback
