services:
  e2e:
    image: RUNNER_IMAGE
    build:
    profiles: [e2e]

  system:
    images: RUNNER_IMAGE
    build:
    profiles: [system]

  webapp:
    image: WEBAPP_IMAGE
    build:
    profiles: [e2e]

  backend:
    image: BACKEND_IMAGE
    build:
    profiles: [e2e, system]
