version: '3.7'
services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file:
      - .env
  webapp:
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - .env:/app/.env.local