version: '3.7'
services:
  backend:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
  webapp:
    build:
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - .env:/app/.env.local
