name: Build and Run Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # TODO - Optimize. Build images only once.
  # For example, webapp-next is built 3 times now:
  # In build job and once for each backend when testing e2e
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Golang Rest Backend Docker image
        run: docker build -t backend-golang-rest backend-golang-rest
      - name: Build React WebApp Docker image
        run: docker build -t webapp-nextjs webapp-nextjs
  e2e:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        e2e_runner: [cypress]
        frontend: [next]
        backend: [go, js]
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - uses: KengoTODA/actions-setup-docker-compose@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "BACKEND_BASE_URL='http://backend:8080'" > .env
      - name: Run E2E tests
        run: just test-${{ matrix.e2e_runner }}-${{ matrix.frontend }}-${{ matrix.backend }}
