name: Unit Test

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: ["backend-rest-go", "backend-rest-js"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.21.3
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.3
      - uses: extractions/setup-just@v2
      - name: Run unit tests ${{ matrix.component }}
        run: cd ${{ matrix.component }} && just unit-test
